### ISSUE TITLE
Standard Error of the MSEP

### ISSUE THREAD

**Issue by GRussolillo** [bhmevik/pls#12]
Hi, 
Is there a way to extract the numerical values of MSEP standard errors which are showed in the plot called by the function selectNcomp?
Thank you for your help!

**Comment by bhmevik** [comment]
Noy directly, but you can redo the calculations outside the function.  If you look at the code of `selectNcomp`, you will see that the two central lines for calculating the sds are
`allresids <- cbind(origResponse - (sum(origResponse) - 
            origResponse)/(length(origResponse) - 1), object$validation$pred[, 
            1, ] - origResponse)`
and
`residsds <- apply(allresids, 2, sd)/sqrt(nrow(allresids))`.
