### ISSUE TITLE
Best statistic for model description

### ISSUE THREAD

**Issue by wordsmith189** [bhmevik/pls#15]
I am primarily interested in model description: I want to talk about what the model tells me about the structure of the data. Specifically, I want to see which of my 260 predictors cluster together in predicting one of the variables. As such I believe that my best bet is to call the loadings using ``model$loadings`` and to try and make sense of which predictors are clustered in those components that have the highest explanatory power. Do you agree with this? Which statistic should I look to in order to gauge the amount of explanatory power for each component?

**Comment by bhmevik** [comment]
For clustering of variables, plotting the loadings can be a good way, yes.  The default way to plot loadings in the pls package (`plot(loadings(mymodel), comps = 1:3)` or similar) will give you line plots, which are not so interesting wrt. clustering, but you can get a scatterplot with `plot(loadings(mymodel), comps = 1:3, scatter = TRUE)`, which should be more useful.
As for gauging the amount of explanatory power, I typically look at the reduction in RMSEP for each component, for instance by plotting it: `plot(RMSEP(mymod))`.  Note that the model should be validated by cross validation for the RMSEP values to be useful.

**Comment by wordsmith189** [comment]
This makes perfect sense, thanks so much.
