### ISSUE TITLE
plsr: permutation and bootstrap

### ISSUE THREAD

**Issue by johstu** [bhmevik/pls#20]
Hello!

I set up a formula plsr(Age ~ Connectivity, scale=TRUE, data = PLSR, validation = "LOO“) and used RMSEP to decide on how many components to keep. 
However, in a next step I would like to test my model for significance. Is there a procedure integrated directly in the plsr package?
Specifically, I am struggeling with the significance estimation of
1) my model (permutation test) and 
2) of specific saliences or latent variables (bootstrap). 
I have to admit that im just starting to use R for statitsical investigations. If I am sure, that these procedures aren’t part of the plsr package I can further try to build the significance tests myself. I would be really pleased if anyone could help me with some suggestions regarding the validation process.

Kind regards!

**Comment by GerardYu** [comment]
hi, i have used PLS on my connectivity data as well, and have used a custom script for the permutation testing. However, my permutation tests determine the statistical significance of the edges of the brain connectivity (i.e., predictors) and not the statistical significance of the overall model

not sure about the significance estimation of the model, but what I did was to show that in the LOO cross validation, my PLS model predicted scores that significantly correlated with the observed scores. I don't think there is an in-built function to compute the predicted-observed correlation— I had to do it with a custom script too.

**Comment by bhmevik** [comment]
Sorry for the late reply. No, there is no functionalitu\y for testing significance in the pls package. It does implement Jack-Knife estimates of the regression coefficients, which could be used for significance testing of the coefficients (but please do read the warnings in the documentation about this), but nothing for testing significance of predictions or the overall model.

**Comment by johstu** [comment]
Okay thank you!
