### ISSUE TITLE
Why is PRESS0 > TSS?

### ISSUE THREAD

**Issue by mrTomkins** [bhmevik/pls#21]
I am learning to use pls and analyzing the object returned by mvrCv / crossval. While learning, I am also cross checking the results via calculations in excel.

The PRESS0 value appears to be: 
PRESS0 = sample variance * n * [n / (n-1)]

However, I would expect PRESS0 to be:
PRESS0 = Total Sum of Squares = sample variance * (n-1)

Why is PRESS0 being increased to be larger than the total sum of squares?

**Comment by bhmevik** [comment]
The leave-one-out crossvalidated PRESS0 is defined as \Sigma_{i=1}^n (y_i - 1/(n-1) * \Sigma_{j≠i} y_j)^2, and the sample variance, Var(y), as 1/(n-1) * \Sigma_{i=1}^n (y_i - 1/n * \Sigma_{j=1}^n y_j)^2.  If you do the math, you will find that LOO-CV PRESS0 = n^2/(n-1) * Var(y). (The trick is to rewrite \Sigma_{j≠i} y_j as  \Sigma_{j=1}^n y_j - y_i in the PRESS0 formula.)
