### ISSUE TITLE
selectNcomp() for multivariate response?

### ISSUE THREAD

**Issue by wzel** [bhmevik/pls#22]
From `pls/ncomp.R`:

> At this moment only
> for univariate Y [...].

I might be interested in implementing the general approach. Any tips with regard to publication(s) where multivariate versions of one-sigma or randomization heuristics are described?

**Comment by rwehrens** [comment]
Could be useful - however, please be aware that the choice of components is quite heuristic in nature. So I would keep it very simple indeed. If the Ys are scaled you could even add all prediction errors, or apply weights that make sense.

In the Van der Voet paper underlying the permutation approach the authors already point out the possibility of extending this to multivariate data: 

When more response variables are predicted simultaneously, as e.g. in PLS2 or multivariate linear regression, method comparison may involve randomization tests for multivariate analysis of variance [3]. 

[3] ES. Edgington, Randomizarion Tests, Marcel Dekker, New York, 2nd edn., 1987.

 I do not have this book, but it could be worth checking out...

Good luck,
Ron

**Comment by rwehrens** [comment]
did not mean to close this, sorry...

**Comment by wzel** [comment]
Sorry for the late reply. Due to covid-19-related library closures, my possibilities to work on this are virtually nil now. Maybe I will revive this one day.
