### ISSUE TITLE
ability to load data from sparse matrix

### ISSUE THREAD

**Issue by UnixJunkie** [bhmevik/pls#23]
Hello,

I wonder if the package can work with sparse data.
I guess not from the documentation.
But, it would be nice to have (especially without having to go to a dense
representation as an intermediate).

Thanks,
F.

**Comment by bhmevik** [comment]
You are right, there is no support for sparse matrices in the pls package at the moment. I'd have to look at the algorithms, but I suspect the currently implemented algorithms will only work with dense matrices.

**Comment by bhmevik** [comment]
I've looked into this a little more now, and I don't think it is practical to get the algorithms to work with sparse matrices, even if it might be possible. For instance, by default, the matrices are coloumn-centered, which in general will introduce so many non-zero elements that storing them as sparse matrices are counter productive. (For instance, if a coloumn has one element which is 1, and the other n - 1 elements are zero, when you mean center it, it will have one element which is (n-1)/n and the other n - 1 elements are -1/n.) So I don't think we wil implement support for sparse matrices in the pls package, at least for now.

**Comment by UnixJunkie** [comment]
ok, thanks for having looked into it though.
