### ISSUE TITLE
Make formula use optional (formulas don't work with wide data)

### ISSUE THREAD

**Issue by rorynolan** [bhmevik/pls#28]
Formulas don't work with wide data (see https://www.researchgate.net/post/error_protect_protection_stack_overflow_in_R and https://stackoverflow.com/questions/32826906/how-to-solve-protection-stack-overflow-issue-in-r-studio). I run into this problem all the time because I'm fitting models on the gene expression of 50,000 genes. 
This problem is well known and many ML packages facilitate users to avoid formulas (e.g. `recipes`, `xgboost`). Also in base R, functions like `generics::fit_xy()` exist for this purpose. 
Would you be interested in a PR to extend this package in this way?

**Comment by bhmevik** [comment]
If you store every coloumn of your data as its own variable in the data frame, formula handling is not going to work well with very wide data, no. That is why we suggest you group similar coloumns of the data into matrices in the data frames, typically using the `I()` function. Exactly how to do so depends on how your data are stored in the first place. If your X data is already a matrix, you can simply use `mydata <- data.frame(y = y, X = I(X))`.  Then you can use `y ~ X` as your formula. If the X data is a data frame, then `mydata <- data.frame(y = y, X = I(as.matrix(X)))` will work. Similarly if you have several groups of X variables. This will avoid the overhead of formula handling, which can be quite severe.
If you still want to use matrices directly for fitting purposes, you can call the underlying fit functions directly, like `kernel.pls.fit(X, y, ...)`. (Of course, you will then have to do manually all the niceties that `mvr()` and its wrappers do, like scaling and cross-validation, and most of the plot and summary functions expect to get an `mvr` object.)

**Comment by bhmevik** [comment]
As an example, here is an analysis running a leave-one-out cross-validation on a data set of a data set with 56 rows and 49089 coloumns in the X matrix (the data actually contained 82 rows, but some values were missing from the the response variable, so only 56 rows were actually used):
```
> library(pls)

Attaching package: ‘pls’

The following object is masked from ‘package:stats’:

    loadings

>  load("NMR0608.RData")
> gc(reset = TRUE)
          used (Mb) gc trigger (Mb) max used (Mb)
Ncells  320638 17.2     645254 34.5   320638 17.2
Vcells 4687116 35.8   10146329 77.5  4687116 35.8
> system.time(mymod <- plsr(weight ~ bucket, data = NMR, val = "LOO"))
   user  system elapsed 
 99.413   1.083 100.509 
> gc(reset = FALSE)
           used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells   335073  17.9     645254  34.5   645254  34.5
Vcells 18234413 139.2   47736296 364.2 47732018 364.2
```
The max memory usage of the analysis was about 400 megabytes, and it took 100 seconds.  (There is a fit method `method = widekernelps` that is specially designed for wide data. On this data set, it finished in ab 65 seconds, but actually used a little more memory: 560 megabytes. It is an iterative algorithm, so its speed and accuracy depends on how well the algorithm converges.)

Here is a comparison of a single fit using `plsr()` vs. calling the fit function directly:
```
> system.time(mymod <- plsr(weight ~ bucket, data = NMR))
   user  system elapsed 
  1.704   0.024   1.728 
> system.time(mymod <- kernelpls.fit(X, y, ncomp = 55))
   user  system elapsed 
  1.544   0.012   1.556 
```
(`X` and `y` are the data that `plsr()` would send to the internal call of `kernelpls.fit()`.) So `plsr()` spent only about 0.2 seconds on formula handling and wrapping up the answer afterwards. The memory usage of both calls was almost identical too.

**Comment by rorynolan** [comment]
This is interesting and a great answer to my question. Thanks a lot.
I have never seen this option of using a matrix column. I knew they existed, but I didn't know they would be interpreted correctly when passed through the formula interface. Is this documented somewhere? This solves my problem. I was actually using `pls` through the recipes package. When I use wide data frames with this package, it goes with the regular data frame one variable per column formula interface without any of this matrix column magic. I will try to submit a PR there to take advantage of this functionality that you provide for wide data.
Would you be interested in a PR to extend your documentation to include advice on wide data handling?

**Comment by bhmevik** [comment]
Very good that it solved the issue for you! At the time I wrote the package, I didn't document (in the package itself) the use of matrices in data frames, because it is standard; the same thing will work with, for intance, `lm()`.  However, I guess many people are not aware of the feature. So yes, a PR for documenting it would be very welcome.

**Comment by rorynolan** [comment]
Happy to do this. Could you please point me to where this behaviour is documented for `lm()`? I can't find it anywhere. It would be helpful to read before doing the PR.

**Comment by rorynolan** [comment]
Dear @bhmevik 
I no longer have the time to do this. To be honest I've started using the mixOmics package for PLS because it has a more obvious interface for doing what I need.
Thank you for all your help,
Rory
