### ISSUE TITLE
Obtain intercepts from Jackknife cross validation

### ISSUE THREAD

**Issue by JulienLamour** [bhmevik/pls#30]
Hello, 
Is it currently possible to obtain the intercepts obtained by the jackknife crossvalidation? 
For example, if we use jackknife = TRUE with 100 segments, I see the 100 coefficients in object$validation$coefficients but I can't find the 100 intercepts. This would be nice to calculate confidence interval of the prediction using the jackknife method already implemented, or to calculate other statistics. 
Could it be possible to update the coef function to make it work with the validation coefficients?
I hope I didn't miss something.. 
Thanks

**Comment by khliland** [comment]
PCR/PLS in default settings work on centered data. Therefore there is no need to calculate intercepts. This is in line with the coefficients for the main model having no intercept values.
