### ISSUE TITLE
pls package example in R

### ISSUE THREAD

**Issue by Catrin-Landseer** [bhmevik/pls#32]
In the gasoline dataset used as an example for the pls run-through in R, I am unsure about how the NIR values are obtained. How were all 401 diffuse reflectance measurements condensed from a range of 900 to 1700 nm into a single NIR value? Were the octane numbers known before too? Thanks.

**Comment by khliland** [comment]
The NIR part of the gasoline data.frame contains a matrix of 401 columns (2 nm spacing from 900 to 1700 nm). You will find the description of the data set if you attach the pls package and write ?gasoline in the console.

**Comment by Catrin-Landseer** [comment]
Yes, thanks for the reply. I've had a look at the description of the dataset and am aware of the matrix of 401 columns, but am still confused about how a single NIR value was obtained - surely there are reflectance values for each wavelength. At what wavelength were those NIR values taken? Or is one NIR value an average reflectance across a range of wavelengths? Thanks

**Comment by khliland** [comment]
I am not quite sure where the single NIR value comes in. The data.frame called _gasoline_ contains two elements:  
- _octane_ is a vector of length 60 containing the octane number of each sample measured using reference analyses. 
- _NIR_ is a matrix of size 60x401 containing 60 NIR spectra. For a given sample, the 401 columns are measurements of the same sample at 401 equally spaced wavelengths in the region 900, 902, 904, ... 1700 nm, i.e. the diffuse reflectance in log(1/R) at the measured wavelengths.

**Comment by Catrin-Landseer** [comment]
Okay, that's great. Thank you!
