### ISSUE TITLE
Repeated k-fold CV

### ISSUE THREAD

**Issue by dominix88** [bhmevik/pls#4]
Hi,
thanks for the great package.
Is there a way to run repeated k-fold CV to get a standard error for the prediction loss?

**Comment by bhmevik** [comment]
Estimation of stderr for prediction loss by repeated k-fold CV is not implemented, no. However, the selectNcomp() function to select optimal number of components estimates the stderr from the cross-validation residuals when called with method = "onesigma". Perhaps you can use that.  See ?selectNcomp (especially the Details section).  You can also look at the code of selectNcomp to see how the stderr is calculated.
