### ISSUE TITLE
Help function

### ISSUE THREAD

**Issue by hcpetersen** [bhmevik/pls#5]
Dear Authors of pls,
May I suggest that you add information on the option maxit to the help function for mvr (plsr, etc).
Best
Hans

**Comment by bhmevik** [comment]
Thanks for the suggestion!
I'll have to think a little about how that could be done. The thing is that "maxit" and "tolerance" are not arguments of mvr() or plsr(), but of some of the underlying fit functions (oscorespls.fit and widekernelpls.fit), so just adding them amongst the arguments in the mvr help page will give an error when checking the package for submission to CRAN. I'll have to check if there are other ways of mentioning them there, or whether it is best to make them arguments of mvr() directly.
(There is the same consideration for other functions that are not usually called directly, like mvrCv().)

**Comment by bhmevik** [comment]
I've added these arguments in the documentation of the "..." argument.  See pull request #7 . It is not optimal, but I didn't want to promote all those arguments to the mvr() function; it already has enough arguments. :)
